In [4]:
import numpy as np

**Creating arrays**

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [4]:
np.full(7, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [6]:
numbers = np.array([1,2,3,7,5,12])

In [7]:
numbers[2]

np.int64(3)

In [8]:
numbers[2] = numbers[2]*10

In [9]:
numbers[2]

np.int64(30)

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**multi-dimensional arrays**

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
multi_dim = np.array([
    [1,2,3],
    [4,5,6]
])

multi_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
multi_dim[1]

array([4, 5, 6])

In [18]:
multi_dim[0,1]

np.int64(2)

In [20]:
multi_dim[:,1]

array([2, 5])

**Randomly generated arrays**

In [23]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [25]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [24]:
np.random.randint(low=0, high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

**element-wise operations**

In [26]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
a + 7

array([ 7,  8,  9, 10, 11, 12, 13])

In [29]:
bigger_numbers = (15 + (a *2 )**2)/5
bigger_numbers

array([ 3. ,  3.8,  6.2, 10.2, 15.8, 23. , 31.8])

In [30]:
a + bigger_numbers

array([ 3. ,  4.8,  8.2, 13.2, 19.8, 28. , 37.8])

**comparison operations**

In [31]:
a > bigger_numbers

array([False, False, False, False, False, False, False])

In [33]:
a[a < bigger_numbers]

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
a[True]

array([[0, 1, 2, 3, 4, 5, 6]])

**Summarizing operations**

In [35]:
a.max()

np.int64(6)

In [36]:
a.min()

np.int64(0)

In [37]:
a.sum()

np.int64(21)

In [38]:
a.mean()

np.float64(3.0)

In [39]:
a.std()

np.float64(2.0)

**multiplication**

In [18]:
u_vector = np.array([1,2,3,4])
v_vector = np.array([2,2,2,2])

In [19]:
u_vector.shape

(4,)

In [20]:
v_vector.shape

(4,)

In [102]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0
    for i in range(n):
        row_summa = u[i]*v[i]
        result += row_summa
        row_summa = 0
    return result

oppa = vector_vector_multiplication(u_vector, v_vector)
oppa

np.int64(20)

In [103]:
u_vector.dot(v_vector)

np.int64(20)

**Matrix-Vector Multiplication**

In [104]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
v = np.array([8,5,3,1])

In [105]:
U.shape

(3, 4)

In [106]:
U[0].shape

(4,)

In [107]:
v.shape

(4,)

In [108]:
U.shape == v.shape[0]

False

In [109]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    n = v.shape[0]
    k = U.shape[0]
    # print("k", k)
    # print("n", n)
    result_array = [0,0,0]

    for j in range(k): 
        result = 0
        for i in range(n):
            # print("U[j]", U[j])
            # print("Row", U[j][i], "*", v[i])
            row = U[j][i]*v[i]
            result += row
            # print("result", result)
            # print(j)
        result_array[j] = result
    return result_array

In [110]:
oppa_lala = matrix_vector_multiplication(U, v)
oppa_lala

[np.int64(57), np.int64(23), np.int64(36)]

In [111]:
def matrix_vector_multi_refactored(U, v):
    assert U.shape[1] == v.shape[0]

    k = U.shape[0]
    result_array = np.zeros(k) #[0,0,0]

    for j in range(k): 
        result_array[j] = vector_vector_multiplication(U[j], v)
    return result_array

In [112]:
trulala = matrix_vector_multiplication(U, v)
trulala

[np.int64(57), np.int64(23), np.int64(36)]

In [113]:
U.dot(v)

array([57, 23, 36])

In [114]:
V = np.array([
    [1,1,2],
    [0, 0.5, 1],
    [0,2,1],
    [2,1,0]
])

In [121]:
def matrix_matrix_multiplied(U, V):
    assert U.shape[1] == V.shape[0]
    col_num = V.shape[1]
    row_num = V.shape[0] # U.shape[1]
    print(col_num)

    result_matrix = np.zeros((row_num, col_num))
    
    for z in range(col_num):
        print("V[:,z]", V[:,z])
        print("U shape", U.shape[1])
        print("shape V[:,z]", V[:,z].shape[0])
        result_matrix[z] = matrix_vector_multi_refactored(U, V[:,z]) 
    return result_matrix

In [122]:
matrix_matrix_multiplied(U, V)

3
V[:,z] [1. 0. 0. 2.]
U shape 4
shape V[:,z] 4
V[:,z] [1.  0.5 2.  1. ]
U shape 4
shape V[:,z] 4
V[:,z] [2. 1. 1. 0.]
U shape 4
shape V[:,z] 4


array([[14. ,  5. ,  5. ],
       [20. ,  6. ,  8.5],
       [13. ,  5. ,  9. ],
       [ 0. ,  0. ,  0. ]])

In [123]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**Identity matrix**

In [124]:
I = np.eye(5)

In [125]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Inverse matrix**

In [127]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [128]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [129]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])